version: "3"
services:
  node:
    image: node:16
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - node-module-volume:/workspace/node_modules
      - nuxt-volume:/workspace/.nuxt
    ports:
      - 3000:3000
    command: "yarn dev"
volumes:
  node-module-volume:
  nuxt-volume:
